
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
 

config:
frontend:
history:
logbook:
sun:
system_health:
updater:
# map:
# mobile_app:
# person:
# cloud:
# ssdp:
# zeroconf:

logger:
    default: warning



# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
#tts:
#  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named scripts

homeassistant:
    packages: !include_dir_named packages


python_script:



api:

tuya:
    username: !secret tuya_username
    password: !secret tuya_password
    country_code: !secret tuya_country_code


media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

