
sensor:
- platform: time_date
  display_options:
      - 'time'


#  Champ de saisie de l'heure de reveil       
input_datetime:
    alarm_time:
        name: Horaire de réveil
        has_date: false
        has_time: true
        icon: mdi:alarm


group:
    wake_up:
        name: Réveil ☀️
        entities:
        - input_datetime.alarm_time
        - automation.reveil_musical  
        - automation.reveil_lumineux
          #- input_boolean.alarm_status

          
automation:

# Réveil avec une playlist
- alias: Réveil musical
  trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.alarm_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  action:
      service: python_script.fade_in_playlist
      data:
        duration: 300
        playlist: spotify:playlist:5PKh6LXvxvF2860ylwdPtJ

# Réveil en lumière
- alias: Réveil lumineux
  trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.alarm_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  action:
      service: python_script.transition_light
      data:
        entity_id: light.chambre
        duration: 300 # 10 mn


homeassistant:
    customize: 
        automation.reveil_lumineux:
            icon: mdi:lightbulb-on-outline
        automation.reveil_musical:
            icon: mdi:music